export enum LocationType {
  AIRPORT = 'AIRPORT',
  HARBOUR = 'HARBOUR',
  RAILWAY = 'RAILWAY',
  COUNTRY = 'COUNTRY',
  AREA = 'AREA',
  HOTEL = 'HOTEL',
  GENERIC_LOCATION = 'GENERIC_LOCATION',
  BUS_STOP = 'BUS_STOP'
}
